name: Generate File List

on:
    push:
        paths:
            - "public/**"
    workflow_dispatch:

permissions:
    contents: write

jobs:
    generate-file-list:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.9"

            - name: Generate file list with Python
              run: |
                  python << 'EOF'
                  import os
                  import datetime
                  from pathlib import Path
                  from zoneinfo import ZoneInfo

                  def generate_file_list():
                      # 日本時間（JST）での現在時刻を取得
                      now_jst = datetime.datetime.now(ZoneInfo("Asia/Tokyo"))
                      
                      html_content = '''<!DOCTYPE html>
                  <html lang="ja">
                  <head>
                      <meta charset="UTF-8">
                      <meta name="viewport" content="width=device-width, initial-scale=1.0">
                      <title>Public Files</title>
                  </head>
                  <body>
                      <h1>Public Files</h1>
                      <p>最終更新（日本時間）: {}</p>
                  '''.format(now_jst.strftime('%Y年%m月%d日 %H:%M:%S'))
                      
                      public_path = Path('public')
                      
                      if not public_path.exists():
                          html_content += '<p>publicフォルダが見つかりません</p>'
                      else:
                          # papers フォルダ
                          papers_path = public_path / 'papers'
                          html_content += '<h2>papers/</h2>\n'
                          if papers_path.exists() and any(papers_path.iterdir()):
                              html_content += '<ul>\n'
                              for subdir in sorted(papers_path.iterdir()):
                                  if subdir.is_dir():
                                      ja_html = subdir / 'ja.html'
                                      en_html = subdir / 'en.html'
                                      ja_pdf = subdir / 'ja.pdf'
                                      en_pdf = subdir / 'en.pdf'
                                      
                                      # HTMLまたはPDFのいずれかが存在する場合のみ表示
                                      if ja_html.exists() or en_html.exists() or ja_pdf.exists() or en_pdf.exists():
                                          html_content += f'    <li>{subdir.name}\n'
                                          
                                          # HTML行（HTMLファイルがある場合のみ）
                                          if ja_html.exists() or en_html.exists():
                                              html_content += '        <ul><li>html: [ '
                                              
                                              if ja_html.exists():
                                                  relative_path = ja_html.relative_to(Path('.'))
                                                  html_content += f'<a href="{relative_path}">ja</a>'
                                              else:
                                                  html_content += 'ja'
                                              
                                              html_content += ' / '
                                              
                                              if en_html.exists():
                                                  relative_path = en_html.relative_to(Path('.'))
                                                  html_content += f'<a href="{relative_path}">en</a>'
                                              else:
                                                  html_content += 'en'
                                              
                                              html_content += ' ]</li>\n'
                                          
                                          # PDF行（PDFファイルがある場合のみ）
                                          if ja_pdf.exists() or en_pdf.exists():
                                              if not (ja_html.exists() or en_html.exists()):
                                                  html_content += '        <ul>'
                                              html_content += '<li>pdf: [ '
                                              
                                              if ja_pdf.exists():
                                                  relative_path = ja_pdf.relative_to(Path('.'))
                                                  html_content += f'<a href="{relative_path}">ja</a>'
                                              else:
                                                  html_content += 'ja'
                                              
                                              html_content += ' / '
                                              
                                              if en_pdf.exists():
                                                  relative_path = en_pdf.relative_to(Path('.'))
                                                  html_content += f'<a href="{relative_path}">en</a>'
                                              else:
                                                  html_content += 'en'
                                              
                                              html_content += ' ]</li>\n'
                                          
                                          html_content += '        </ul>\n    </li>\n'
                              html_content += '</ul>\n'
                          else:
                              html_content += '<p>{blank}</p>\n'
                          
                          # slides フォルダ
                          slides_path = public_path / 'slides'
                          html_content += '<h2>slides/</h2>\n'
                          if slides_path.exists() and any(slides_path.iterdir()):
                              html_content += '<ul>\n'
                              for subdir in sorted(slides_path.iterdir()):
                                  if subdir.is_dir():
                                      ja_html = subdir / 'ja.html'
                                      en_html = subdir / 'en.html'
                                      ja_pdf = subdir / 'ja.pdf'
                                      en_pdf = subdir / 'en.pdf'
                                      
                                      # HTMLまたはPDFのいずれかが存在する場合のみ表示
                                      if ja_html.exists() or en_html.exists() or ja_pdf.exists() or en_pdf.exists():
                                          html_content += f'    <li>{subdir.name}\n'
                                          
                                          # HTML行（HTMLファイルがある場合のみ）
                                          if ja_html.exists() or en_html.exists():
                                              html_content += '        <ul><li>html: [ '
                                              
                                              if ja_html.exists():
                                                  relative_path = ja_html.relative_to(Path('.'))
                                                  html_content += f'<a href="{relative_path}">ja</a>'
                                              else:
                                                  html_content += 'ja'
                                              
                                              html_content += ' / '
                                              
                                              if en_html.exists():
                                                  relative_path = en_html.relative_to(Path('.'))
                                                  html_content += f'<a href="{relative_path}">en</a>'
                                              else:
                                                  html_content += 'en'
                                              
                                              html_content += ' ]</li>\n'
                                          
                                          # PDF行（PDFファイルがある場合のみ）
                                          if ja_pdf.exists() or en_pdf.exists():
                                              if not (ja_html.exists() or en_html.exists()):
                                                  html_content += '        <ul>'
                                              html_content += '<li>pdf: [ '
                                              
                                              if ja_pdf.exists():
                                                  relative_path = ja_pdf.relative_to(Path('.'))
                                                  html_content += f'<a href="{relative_path}">ja</a>'
                                              else:
                                                  html_content += 'ja'
                                              
                                              html_content += ' / '
                                              
                                              if en_pdf.exists():
                                                  relative_path = en_pdf.relative_to(Path('.'))
                                                  html_content += f'<a href="{relative_path}">en</a>'
                                              else:
                                                  html_content += 'en'
                                              
                                              html_content += ' ]</li>\n'
                                          
                                          html_content += '        </ul>\n    </li>\n'
                              html_content += '</ul>\n'
                          else:
                              html_content += '<p>{blank}</p>\n'
                      
                      html_content += '''</body>
                  </html>'''
                      
                      with open('index.html', 'w', encoding='utf-8') as f:
                          f.write(html_content)
                      
                      print("index.html が生成されました")

                  generate_file_list()
                  EOF

            - name: Commit changes
              run: |
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add index.html
                  if git diff --staged --quiet; then
                    echo "No changes to commit"
                  else
                    git commit -m "Auto-update file list [bot]"
                    git push
                  fi
